### ISSUE TITLE
Whitespaces after operators (=, :, ||, etc.) in Vimscript files are not shown

### ISSUE THREAD

**Issue by Coacher** [chrisbra/vim-show-whitespace#2]
$SUBJ

**Comment by chrisbra** [comment]
That is a known vim problem and is described in the help. See here for a patch to fix this in Vim:
https://groups.google.com/d/msg/vim_dev/sSkuUhSDX6o/fEWBkaseeoUJ

**Comment by Coacher** [comment]
I see. Thanks for the info.
