### ISSUE TITLE
[PATCH] vim-show-whitespace doesn't preserve user's 'list' option after untoggle

### ISSUE THREAD

**Issue by Coacher** [chrisbra/vim-show-whitespace#5]
Hello.

I have 'list' option enabled permanently to highlight trailing spaces and tabs.

If I run `ShowWhiteToggle` twice, trailing spaces and tabs (and other listchars) are not highlighted anymore, because vim-show-whitespace abruptly disabled it [here](https://github.com/chrisbra/vim-show-whitespace/blob/master/autoload/showwhite.vim#L86).

It would be nice if this plugin would preserve user's 'list' setting instead of flipping it unconditionally.

Thanks.

Update: use proper plugin name.

**Comment by Coacher** [comment]
Here's a simple patch for you to fix this.

```
From b20fc87264a1dbe62b0f700a7feee51094822dcb Mon Sep 17 00:00:00 2001
From: Ilya Tumaykin <itumaykin@gmail.com>
Date: Wed, 9 Dec 2015 01:41:15 +0300
Subject: [PATCH] Preserve user's 'list' option setting after untoggle

Remove trailing spaces on the way.
---
 autoload/showwhite.vim | 10 +++++++---
 1 file changed, 7 insertions(+), 3 deletions(-)

diff --git a/autoload/showwhite.vim b/autoload/showwhite.vim
index 5362092..ea76d0e 100644
--- a/autoload/showwhite.vim
+++ b/autoload/showwhite.vim
@@ -6,10 +6,14 @@
 " Script: http://www.vim.org/scripts/script.php?script_id=
 " Copyright:    © 2014 by Christian Brabandt
 "               The VIM LICENSE applies to ShowWhite.vim
-"               (see |copyright|) except use "ShowWhite.vim" 
+"               (see |copyright|) except use "ShowWhite.vim"
 "               instead of "Vim". No warranty, express or implied.
 "               *** ***   Use At-Your-Own-Risk!   *** ***
 " GetLatestVimScripts:  5043 2 :AutoInstall: showwhite.vim
+
+" Save 'list' option setting to restore it after untoggle
+let s:save_list = &list
+
 fun! <sid>WarningMsg(msg) "{{{1
     let msg = "ShowWhite: ". a:msg
     echohl WarningMsg
@@ -83,10 +87,10 @@ fun! showwhite#Init() "{{{1
         else
             let space = matchstr(&listchars, 'space:.')
             exe ":setl listchars-=".space
-            set nolist
+            let &list = s:save_list
         endif
     endif
-endfun 
+endfun

 " Modeline {{{1
 " vim: ts=4 sts=4 fdm=marker com+=l\:\" fdl=0 et
-- 
2.5.4
```

**Comment by chrisbra** [comment]
I just pushed a change. Can you check, that this works for you?

Thanks for the feedback.

Best,

## Christian

Der echte Schüler lernt aus dem Bekannten. Das Unbekannte entwickeln
und nähert sich dem Meister. 
        -- Johann Wolfgang von Goethe

**Comment by Coacher** [comment]
No. The issue is not fixed by this commit.

Update: because you are still flipping 'list' option unconditionally.

**Comment by chrisbra** [comment]
On Di, 08 Dez 2015, Coacher wrote:

> No. The issue is not fixed by this commit.

Okay, I have just pushed a similar fix as you proposed. Should work now 
for you.

Best,

## Christian

Herr, du hast mir das Können genommen, so nimm mir auch noch das Wollen.

**Comment by Coacher** [comment]
Yes. Now it is properly fixed.

Thank you.

**Comment by Coacher** [comment]
I am sorry. I've just realised that in the OP I referred to 'vim-diff-enhanced', which is another your plugin I use and enjoy, instead of 'vim-show-whitespace'. Somehow these two mixed in my head when I was looking at the list of installed plugins yesterday night. I am glad you were able to decipher that)

**Comment by chrisbra** [comment]
Hi Coacher!

On Mi, 09 Dez 2015, Coacher wrote:

> I am sorry. I've just realised that in the OP I referred to
> 'vim-diff-enhanced', which is another your plugin I use and enjoy,
> instead of 'vim-show-whitespace'. Somehow these two mixed in my head
> when I was looking at the list of installed plugins yesterday night. I
> am glad you were able to decipher that)

No problem, it did confuse me initially, but I figured it out.

Note I just pushed a small change, that should work toggling better, 
even if one manually sets list mode later. Please test and verify 
everything still works for you correctly.

Best,

## Christian

Ein Mensch ohne Träume ist wie ein Boot ohne Segel und
Ruder.
        -- Benjamin Stramke

**Comment by Coacher** [comment]
It works fine. Thanks.
